# Generated by Django 4.2.5 on 2023-10-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(max_length=100)),
                ('catg_title', models.CharField(max_length=200)),
                ('catg_description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('catg_tag', models.CharField(max_length=100)),
                ('catg_image', models.ImageField(height_field=556, help_text='Image size: Width=1301 pixel. Height=556 pixel', upload_to='', width_field=1301)),
                ('catg_thumbnail', models.ImageField(height_field=264, help_text='Image size: Width=433 pixel. Height=264 pixel', upload_to='', width_field=433)),
                ('catg_isactive', models.BooleanField(default=True)),
                ('catg_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LDHapp.authormodel')),
            ],
        ),
    ]
