# Generated by Django 4.2.5 on 2023-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='catg_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='catg_image',
            field=models.ImageField(blank=True, height_field=556, help_text='Image size: Width=1301 pixel. Height=556 pixel', null=True, upload_to='', width_field=1301),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='catg_thumbnail',
            field=models.ImageField(blank=True, height_field=264, help_text='Image size: Width=433 pixel. Height=264 pixel', null=True, upload_to='', width_field=433),
        ),
    ]
