# Generated by Django 4.2.5 on 2023-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0003_alter_authormodel_author_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(max_length=100)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=100, null=True)),
                ('catg_tag', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(blank=True, height_field=556, help_text='Image size: Width=1301 pixel. Height=556 pixel', null=True, upload_to='', width_field=1301)),
                ('blog_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='catg_author',
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
