# Generated by Django 4.2.5 on 2023-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0004_blogmodel_remove_categorymodel_catg_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_image',
            field=models.ImageField(blank=True, help_text='Image size: Width=1301 pixel. Height=556 pixel', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='catg_tag',
            field=models.JSONField(),
        ),
    ]
