# Generated by Django 4.2.5 on 2023-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0005_blogmodel_blog_views_alter_blogmodel_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
