# Generated by Django 4.2.5 on 2023-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0006_alter_blogmodel_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='catg_tag',
            field=models.CharField(max_length=100),
        ),
    ]
