# Generated by Django 4.2.5 on 2023-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0007_alter_blogmodel_catg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='catg_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
