# Generated by Django 4.2.5 on 2023-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0008_alter_blogmodel_catg_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_views',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='catg_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='catg_tag',
            field=models.JSONField(null=True),
        ),
    ]
