# Generated by Django 3.1.14 on 2023-10-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0009_remove_blogmodel_blog_views_blogmodel_catg_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=100, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('catg_views', models.IntegerField(default=0)),
                ('blog_image', models.ImageField(blank=True, help_text='Image size: Width=1301 pixel. Height=556 pixel', null=True, upload_to='media/')),
                ('blog_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.AddField(
            model_name='blog',
            name='catg_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blblogapp.categorie'),
        ),
        migrations.AddField(
            model_name='blog',
            name='catg_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blblogapp.tag'),
        ),
    ]
