# Generated by Django 4.2.5 on 2023-10-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0011_alter_blog_id_alter_categorie_id_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catg_tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='catg_tag',
            field=models.ManyToManyField(to='blblogapp.tag'),
        ),
    ]
