# Generated by Django 4.2.5 on 2023-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0012_remove_blog_catg_tag_blog_catg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.JSONField(),
        ),
    ]
