# Generated by Django 4.2.5 on 2023-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0013_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
