# Generated by Django 4.2.5 on 2023-10-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blblogapp', '0014_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='catg_tag',
            new_name='tag_name',
        ),
    ]
